name: Docker Image
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

permissions: write-all

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t tg_attendances_bot --no-cache .
      - name: Publish to ghcr.io
        run: |
          IMAGE_TAG=$(echo "${{ github.ref_name }}" | sed 's/\//_/g')
          if [[ $IMAGE_TAG -eq "main" ]]; then IMAGE_TAG="latest"; fi
          IMAGE_NAME=ghcr.io/ileonidze/tg_attendances_bot:$IMAGE_TAG
          docker tag tg_attendances_bot $IMAGE_NAME
          echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push $IMAGE_NAME
